export const GET_ITEMS = "GET_ITEMS";
export const GET_ITEMS_SUCCESS = "GET_ITEMS_SUCCESS";
export const GET_ITEMS_FAIL = "GET_ITEMS_FAIL";

export const GET_ITEMS_DETAILS = "GET_ITEMS_DETAILS";
export const GET_ITEMS_DETAILS_SUCCESS = "GET_ITEMS_DETAILS_SUCCESS";
export const GET_ITEMS_DETAILS_FAIL = "GET_ITEMS_DETAILS_FAIL";
export const GET_ITEMS_DETAILS_RESET = "GET_ITEMS_DETAILS_RESET";